### ISSUE TITLE
Figures coming out from `list balances` do not match my bank account

### ISSUE THREAD

**Issue by sebinsua** [sebinsua/teller-cli#8]
Figures coming out from `list balances` do not match my bank account.

This seems to relate to missing transactions, however it might also be due to a problem with the hastily written logic. Will solve as a matter of #1.

**Comment by stevegraham** [comment]
I've turned off updating accounts while I implemented a smarter algorithm for updating them. Before all accounts were updated every 15 minutes, now they update in an exponentially increasing interval which is reset each time an account is accessed, such that more frequently accessed accounts are updated more often. I'll be deploying this in the next couple of days.

**Comment by sebinsua** [comment]
Awesome. I'll see whether that fixes this.
